spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/tunely}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: never

server:
  port: ${PORT:8080}
